M48
; DRILL file {KiCad 9.0.6} date 2026-03-11T18:21:47+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-11T18:21:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X155.8Y-100.96
X155.8Y-106.74
T2
X127.75Y-94.5
X127.75Y-125.0
X158.25Y-94.5
X158.25Y-125.0
M30
